version: "3.1"
services:
   postgres:
      image: postgres:latest
      restart: always
      environment: 
        POSTGRES_PASSWORD: miqbalrr
        POSTGRES_USER: miqbalrr
        POSTGRES_DB: todos
      ports:
        - 5432:5432